src/usr/local/buildpack/tools/php.sh, test/php/Dockerfile
Use our prebuild php binaries.
closes #9
=> feat(php): use prebuild binaries

Dockerfile, Dockerfile.bionic, docs/custom-base-image.md, src/usr/local/bin/install-apt, src/usr/local/bin/install-buildpack, src/usr/local/bin/install-gem, src/usr/local/bin/install-pip, src/usr/local/bin/install-tool, src/usr/local/buildpack/tools/composer.sh, src/usr/local/buildpack/tools/php.sh, src/usr/local/buildpack/util.sh, test/php/Dockerfile
Allow to run `install-tool composer 2.0.0` as user
closes renovatebot/docker-php#7
ref: renovatebot/renovate#2355. renovatebot/renovate#8497
=> feat(composer): allow dynamic install

Dockerfile.bionic, src/usr/local/buildpack/tools/java.sh, test/java/Dockerfile
This ppa has more java versions available
https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa
=> feat(java): use ppa with more versions

src/usr/local/buildpack/tools/git.sh, src/usr/local/buildpack/tools/java.sh
Seen it in ws images and tests, where multiple jdk's are installed
=> fix: do not add apt sources twice

src/usr/local/buildpack/tools/composer.sh, src/usr/local/buildpack/tools/elixir.sh, src/usr/local/buildpack/tools/gradle.sh, src/usr/local/buildpack/tools/terraform.sh
- quiet unzip
- wrong version compare for composer
=> fix: quiet and string compare

.github/workflows/build.yaml, README.md, docker-bake.hcl, test/java/Dockerfile
- rename build targets
- add docs
=> chore: update build commands and add docs

test/java/Dockerfile
also tested on renovate branch
=> test(java): gradle v7 support

Dockerfile, src/usr/local/bin/install-buildpack, src/usr/local/buildpack/tools/docker.sh, src/usr/local/buildpack/tools/dotnet.sh, src/usr/local/buildpack/tools/elixir.sh, src/usr/local/buildpack/tools/gradle.sh, src/usr/local/buildpack/tools/helm.sh, src/usr/local/buildpack/tools/nix.sh, src/usr/local/buildpack/tools/node.sh, src/usr/local/buildpack/tools/poetry.sh, src/usr/local/buildpack/tools/powershell.sh, src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/ruby.sh, src/usr/local/buildpack/tools/rust.sh, src/usr/local/buildpack/tools/swift.sh, src/usr/local/buildpack/tools/terraform.sh, src/usr/local/buildpack/tools/yarn.sh, src/usr/local/buildpack/util.sh, test/erlang/Dockerfile, test/python/Dockerfile
- we now override `HOME=/home/$USER_NAME` if a random user is used which gets `HOME=/` by docker by default
- fixed / unified some env handling
=> feat: auto home handling

.github/workflows/build.yaml
Do not run workflow on local pr pushes
=> ci: filter local pr

src/usr/local/buildpack/tools/gradle.sh, src/usr/local/buildpack/tools/java.sh, src/usr/local/buildpack/tools/maven.sh, src/usr/local/buildpack/tools/sbt.sh, src/usr/local/buildpack/tools/scala.sh, test/java/Dockerfile, test/java/test/sbt/build.sbt, test/java/test/sbt/src/main/scala/example/Hello.scala
=> feat(java): add tools

Dockerfile, Dockerfile.bionic, docs/custom-base-image.md, src/usr/local/bin/install-buildpack, src/usr/local/buildpack/util.sh, test/latest/Dockerfile, test/php/Dockerfile
Defining user name and id is now optional and falls back to `user` and `1000`
=> feat: optional user

test/latest/Dockerfile
`TF_PLUGIN_CACHE_DIR` should exist
=> test: create folder

docs/custom-base-image.md, docs/custom-root-ca.md, src/usr/local/bin/install-buildpack, test/latest/Dockerfile
=> feat: detect and install global certs

docs/custom-root-ca.md, src/usr/local/buildpack/tools/node.sh, test/latest/Dockerfile
=> feat(node): use openssl ca certificates

Dockerfile.bionic, src/usr/local/buildpack/tools/git-lfs.sh, test/latest/Dockerfile
Adds git-lfs install tool
Superseeds #15
=> feat: add git-lfs installer

src/usr/local/buildpack/tools/gradle.sh, test/java/Dockerfile
=> feat(java): allow dynamic gradle install

src/usr/local/buildpack/tools/poetry.sh, test/python/Dockerfile
- use new installer, old one is deprecated
- #123
=> feat(poetry): use new installer

.github/workflows/build.yaml, Dockerfile, docker-bake.hcl, src/usr/local/bin/install-buildpack, src/usr/local/buildpack/util.sh
=> feat: upgrade base image via apt

tools/prepare-proxy.js
I think this is the missing part
=> ci: update apt sources before install

test/Dockerfile.bionic, test/latest/Dockerfile, test/python/Dockerfile
Reverts containerbase/buildpack#155
=> test: Revert "test(deps): update dependency python to v3.10.0"

test/java/Dockerfile
No change was necessary, but test refactored to ensure it's tested.
Closes #178
=> test: maven non-root install

src/usr/local/buildpack/tools/dotnet.sh, test/dotnet/Dockerfile, test/dotnet/test/packages.lock.json, test/dotnet/test/test.csproj
=> feat(dotnet): support multiple versions

.github/workflows/build.yaml, src/usr/local/buildpack/tools/jb.sh, test/Dockerfile.bionic, test/jb/Dockerfile, test/jb/test/jsonnetfile.json, test/jb/test/jsonnetfile.lock.json
- Closes #195 
- Relates to https://github.com/renovatebot/renovate/pull/12720
=> feat: add package manager jsonnet-bundler (jb)

test/latest/Dockerfile
=> test: install non-root terraform

src/usr/local/buildpack/tools/node.sh, src/usr/local/buildpack/tools/npm.sh, test/node/Dockerfile
install npm to a versioned folder: `<installDir>/npm/<version>`
=> feat: npm user install

src/usr/local/buildpack/tools/helm.sh, test/helm/Dockerfile
=> feat: allow helm non-root install

src/usr/local/buildpack/tools/yarn-slim.sh, test/node/Dockerfile
creates a `yarn-slim` executable with the renovate no-install patch
=> feat(node): add slim yarn

src/usr/local/buildpack/tools/composer.sh, src/usr/local/buildpack/tools/helm.sh, src/usr/local/buildpack/tools/java-jre.sh, src/usr/local/buildpack/tools/java.sh, src/usr/local/buildpack/tools/jb.sh, src/usr/local/buildpack/tools/lerna.sh, src/usr/local/buildpack/tools/maven.sh, src/usr/local/buildpack/tools/npm.sh, src/usr/local/buildpack/tools/php.sh, src/usr/local/buildpack/tools/pnpm.sh, src/usr/local/buildpack/tools/poetry.sh, src/usr/local/buildpack/tools/powershell.sh, src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/sbt.sh, src/usr/local/buildpack/tools/scala.sh, src/usr/local/buildpack/tools/terraform.sh, src/usr/local/buildpack/tools/yarn.sh
- simplify env update
- use symlinks where apropriate
=> feat: use symlinks

src/usr/local/buildpack/tools/npm.sh, src/usr/local/buildpack/util.sh, test/node/Dockerfile
`node-gyp` upgrade command had missing `NPM_CONFIG_PREFIX` env
=> fix(node): npm path issues

src/usr/local/bin/install-buildpack, src/usr/local/bin/install-gem, src/usr/local/buildpack/tools/composer.sh, src/usr/local/buildpack/tools/docker.sh, src/usr/local/buildpack/tools/dotnet.sh, src/usr/local/buildpack/tools/elixir.sh, src/usr/local/buildpack/tools/golang.sh, src/usr/local/buildpack/tools/gradle.sh, src/usr/local/buildpack/tools/helm.sh, src/usr/local/buildpack/tools/jb.sh, src/usr/local/buildpack/tools/lerna.sh, src/usr/local/buildpack/tools/maven.sh, src/usr/local/buildpack/tools/npm.sh, src/usr/local/buildpack/tools/php.sh, src/usr/local/buildpack/tools/pnpm.sh, src/usr/local/buildpack/tools/poetry.sh, src/usr/local/buildpack/tools/powershell.sh, src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/ruby.sh, src/usr/local/buildpack/tools/rust.sh, src/usr/local/buildpack/tools/sbt.sh, src/usr/local/buildpack/tools/scala.sh, src/usr/local/buildpack/tools/swift.sh, src/usr/local/buildpack/tools/terraform.sh, src/usr/local/buildpack/tools/yarn-slim.sh, src/usr/local/buildpack/tools/yarn.sh, test/dotnet/Dockerfile, test/node/Dockerfile, test/python/Dockerfile, test/ruby/Dockerfile
=> feat: use links and move binaries

.github/workflows/build.yaml, src/usr/local/buildpack/tools/flux.sh, test/Dockerfile.bionic, test/latest/Dockerfile
Needed for https://github.com/renovatebot/renovate/pull/13675.
Haven't tried testing this yet.
=> feat: Add flux tool.

src/usr/local/buildpack/tools/composer.sh, src/usr/local/buildpack/tools/flux.sh, src/usr/local/buildpack/tools/gradle.sh, src/usr/local/buildpack/tools/helm.sh, src/usr/local/buildpack/tools/java-jre.sh, src/usr/local/buildpack/tools/java.sh, src/usr/local/buildpack/tools/jb.sh, src/usr/local/buildpack/tools/lerna.sh, src/usr/local/buildpack/tools/maven.sh, src/usr/local/buildpack/tools/node.sh, src/usr/local/buildpack/tools/npm.sh, src/usr/local/buildpack/tools/php.sh, src/usr/local/buildpack/tools/pnpm.sh, src/usr/local/buildpack/tools/poetry.sh, src/usr/local/buildpack/tools/powershell.sh, src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/sbt.sh, src/usr/local/buildpack/tools/scala.sh, src/usr/local/buildpack/tools/terraform.sh, src/usr/local/buildpack/tools/yarn-slim.sh, src/usr/local/buildpack/tools/yarn.sh, src/usr/local/buildpack/util.sh, src/usr/local/buildpack/utils/ruby.sh
Refactors the tool path functions for easier handling when we introduce the `prepare-tool` script.
=> refactor: split up tool path functions

src/usr/local/bin/install-buildpack, src/usr/local/buildpack/tools/dotnet.sh, src/usr/local/buildpack/tools/git.sh, src/usr/local/buildpack/tools/java-jre.sh, src/usr/local/buildpack/tools/java.sh, src/usr/local/buildpack/tools/node.sh, src/usr/local/buildpack/tools/php.sh, src/usr/local/buildpack/tools/powershell.sh, src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/ruby.sh, src/usr/local/buildpack/tools/swift.sh, src/usr/local/buildpack/util.sh, test/java/Dockerfile
Builds on top of #258 
Solves the remaining shellcheck errors
=> fix: shellcheck errors

.github/workflows/build-push.yaml, .github/workflows/build.yaml
=> ci: add shellcheck

src/usr/local/buildpack/util.sh, src/usr/local/buildpack/utils/environment.sh, src/usr/local/buildpack/utils/filesystem.sh, src/usr/local/buildpack/utils/linking.sh
Move functions from `util.sh` into their own files.
This is the starting step to refactor and tests the utils functions
=> refactor: split util.sh into smaller helper files for better testing

src/usr/local/buildpack/util.sh, src/usr/local/buildpack/utils/filesystem.sh, test/bash/filesystem.bats, test/bash/util.bats
This adds more filesystem helpers and corresponding tests
Additional we are adding a `check` function that will validate function parameters
=> refactor: more helper functions and tests

src/usr/local/buildpack/utils/filesystem.sh, test/bash/filesystem.bats
Closes #304
Closes https://github.com/whitesource/renovate-on-prem/issues/193 after updating.
=> fix: create tool folders with 775 for openshift

src/usr/local/buildpack/tools/dotnet.sh
Workaround for: 
- NuGet/Home#11607
=> fix(dotnet): create default nuget.config

src/usr/local/buildpack/utils/linking.sh, test/bash/linking.bats, test/node/Dockerfile
Moves the linking path to `/usr/local/bin`
=> feat: move all linking targets to /usr/local/bin

src/usr/local/buildpack/utils/ruby.sh
=> fix(ruby): wrong gem path

test/bash/cache.bats
This is a 6Kb file replacement from our own releases, so should never gone,
- ref #331
=> test: fix test file

src/usr/local/buildpack/utils/constants.sh, src/usr/local/buildpack/utils/filesystem.sh, src/usr/local/buildpack/utils/v2/filesystem.sh, test/bash/filesystem.bats, test/bash/v2/filesystem.bats, test/helm/Dockerfile
Should make tool installation executable by everyone
- closes #334
- closes #335
=> feat: make tool execution as nobody possible

src/usr/local/buildpack/tools/poetry.sh
Reverts containerbase/buildpack#342
=> fix: Revert "fix: use new poetry install url"

src/usr/local/buildpack/tools/dotnet.sh, test/dotnet/Dockerfile
=> fix(dotnet): support v2.2

src/usr/local/bin/prepare-tool, src/usr/local/buildpack/util.sh, src/usr/local/buildpack/utils/prepare.sh, test/bash/prepare.bats
Adds a new script `prepare-tool` which simply calls the `prepare` method of all given tools.
Valid for v2 tools only at the moment.
=> feat: add prepare tool

src/usr/local/buildpack/tools/corepack.sh, test/node/Dockerfile, test/node/test/a/.yarnrc.yml, test/node/test/a/package.json
- ref renovatebot/renovate#15173
=> feat(node): add corepack installer

src/usr/local/buildpack/tools/dotnet.sh, src/usr/local/buildpack/tools/powershell.sh, test/Dockerfile.jammy
=> feat(jammy): dotnet and powershell support

src/usr/local/buildpack/tools/php.sh, test/Dockerfile.jammy
=> feat(jammy): support php and python

src/usr/local/buildpack/tools/python.sh, src/usr/local/buildpack/tools/ruby.sh
We should no longer build ruby or python in the fly
**BREAKING CHANGE**
=> feat!: disable dynamic ruby and python builds

.github/workflows/build.yaml, test/flutter/Dockerfile
=> ci: add flutter test

.github/workflows/build.yaml, .gitignore, Dockerfile, docker-bake.hcl, tools/prepare-release.js
write the buildpack version to `/usr/local/buildpack/version`
=> feat: add version file

test/bash/tools/flux.bats, test/bash/tools/helm.bats, test/bash/tools/node.bats
=> test: trim leading `v`

src/usr/local/buildpack/tools/v2/java-jdk.sh, src/usr/local/buildpack/tools/v2/java.sh, src/usr/local/buildpack/utils/java.sh, test/java/Dockerfile
=> feat(java): simplify installer

src/usr/local/buildpack/tools/v2/java-jdk.sh, src/usr/local/buildpack/tools/v2/java-jre.sh, src/usr/local/buildpack/tools/v2/java.sh, src/usr/local/buildpack/utils/filesystem.sh, src/usr/local/buildpack/utils/java.sh, test/java/Dockerfile
=> feat(java): use central cacerts store

docs/custom-root-ca.md
=> docs(custom-certs): add Java configuration section

src/usr/local/buildpack/tools/terraform.sh, src/usr/local/buildpack/tools/v2/elixir.sh
=> fix: use bsdtar instead of unzip

src/usr/local/bin/install-tool, src/usr/local/bin/prepare-tool
=> fix: cleanup tmp after prepare

Dockerfile, docs/custom-base-image.md, src/usr/local/bin/install-buildpack, test/node/Dockerfile
Rename default user from `user` back to `ubuntu`
- closes #572
=> feat!: rename user to ubuntu

src/usr/local/buildpack/utils/ruby.sh
Cache gem based tools like we do for npm tools
=> feat(ruby): cache gem based tools

src/usr/local/bin/install-npm, src/usr/local/buildpack/tools/v2/node.sh, src/usr/local/buildpack/tools/v2/renovate.sh, src/usr/local/buildpack/utils/node.sh, test/node/Dockerfile
Adds `renovate` install tool
Should i add `source-map-support` for better typescript stack traces?
=> feat(node): add renovate installer

src/usr/local/buildpack/tools/v2/ruby.sh
- fixes https://github.com/renovatebot/renovate/issues/19574
=> fix(ruby): add libyaml for 3.2+

.github/workflows/build.yml, tools/publish-release.js
=> build: cosign image

src/usr/local/buildpack/tools/v2/node.sh, test/node/Dockerfile
=> fix(node): don't overwrite npm

src/usr/local/buildpack/tools/v2/node.sh
- ref #715 
- Change to create version directory after downloading files.
=> fix(node): abort no bin defined

src/usr/local/buildpack/utils/ruby.sh, test/ruby/Dockerfile
=> fix(ruby): install ruby tools with user umask

src/usr/local/buildpack/utils/linking.sh, test/helm/Dockerfile, test/latest/Dockerfile
=> fix: make shell wrapper writable by default user

src/usr/local/bin/install-gem, src/usr/local/bin/install-npm, src/usr/local/bin/install-pip
- #763
- #764
- https://github.com/mend/renovate-on-prem/issues/263
=> feat: redirect known tools from `install-(gem|npm|pip)`

src/usr/local/buildpack/tools/v2/composer.sh, src/usr/local/buildpack/tools/v2/dart.sh, src/usr/local/buildpack/tools/v2/docker.sh, src/usr/local/buildpack/tools/v2/elixir.sh, src/usr/local/buildpack/tools/v2/erlang.sh, src/usr/local/buildpack/tools/v2/flutter.sh, src/usr/local/buildpack/tools/v2/flux.sh, src/usr/local/buildpack/tools/v2/git-lfs.sh, src/usr/local/buildpack/tools/v2/golang.sh, src/usr/local/buildpack/tools/v2/gradle.sh, src/usr/local/buildpack/tools/v2/helm.sh, src/usr/local/buildpack/tools/v2/helmfile.sh, src/usr/local/buildpack/tools/v2/jb.sh, src/usr/local/buildpack/tools/v2/kustomize.sh, src/usr/local/buildpack/tools/v2/maven.sh, src/usr/local/buildpack/tools/v2/nix.sh, src/usr/local/buildpack/tools/v2/powershell.sh, src/usr/local/buildpack/tools/v2/python.sh, src/usr/local/buildpack/tools/v2/rust.sh, src/usr/local/buildpack/tools/v2/sbt.sh, src/usr/local/buildpack/tools/v2/scala.sh, src/usr/local/buildpack/tools/v2/swift.sh, src/usr/local/buildpack/tools/v2/terraform.sh, src/usr/local/buildpack/tools/v2/vendir.sh
most tools now create the version dir after download, so we've less dead installs
- #715
=> fix: create version folder after download

src/usr/local/buildpack/tools/v2/dart.sh, src/usr/local/buildpack/utils/constants.sh, test/Dockerfile.arm64, test/Dockerfile.jammy
=> feat(dart): support arm64 and checksums

src/usr/local/buildpack/utils/prepare.sh, test/Dockerfile.arm64, test/Dockerfile.jammy
=> test: more arm64 tests

test/Dockerfile.arm64
=> test(erlang): enable arm64 tests

test/Dockerfile.arm64
=> test(php): enable arm64 tests

src/usr/local/buildpack/tools/v2/node.sh, test/node/Dockerfile
Try to download from https://github.com/containerbase/node-prebuild and fallback to nodejs.org
=> feat(node): download from github if available

test/node/Dockerfile
=> test(node): remove flaky node install test

src/usr/local/buildpack/tools/v2/erlang.sh, src/usr/local/buildpack/tools/v2/maven.sh, src/usr/local/buildpack/tools/v2/node.sh, src/usr/local/buildpack/tools/v2/php.sh, src/usr/local/buildpack/tools/v2/python.sh, src/usr/local/buildpack/utils/cache.sh, test/java/Dockerfile
older maven versions only have a sha1 file
=> feat(maven): support older sha1 checksums

.github/workflows/trivy.yml
Related:
- https://github.com/renovatebot/docker-renovate-full/pull/1722
- https://github.com/renovatebot/docker-renovate/pull/1342
=> ci: simplify and use valid tag for trivy workflow

src/usr/local/buildpack/util.sh
Filename had missing `.conf` extension.
=> fix(apt): wrong proxy config filename

tools/publish-release.js
=> feat: enable provenance

src/usr/local/bin/install-containerbase, src/usr/local/containerbase/util.sh, src/usr/local/containerbase/utils/cache.sh, src/usr/local/containerbase/utils/constants.sh, src/usr/local/containerbase/utils/environment.sh
=> feat!: drop buildpack compabillity

src/usr/local/containerbase/tools/v2/ruby.sh, src/usr/local/containerbase/utils/ruby.sh
=> feat(ruby): reduce dev tools

src/usr/local/containerbase/tools/v2/yarn-slim.sh, src/usr/local/containerbase/utils/node.sh, test/node/Dockerfile
=> fix(node): use node npm version to install tools

.eslintignore, .eslintrc.cjs, .github/workflows/build.yml, .gitignore, .prettierignore, codecov.yml, package.json, src/cli/services/http.service.spec.ts, src/cli/tsconfig.json, test/global-setup.ts, test/http-mock.ts, tools/esbuild.js, tsconfig.json, vite.config.ts, yarn.lock
add tests as preparation for #1067
=> test: add vitest

src/cli/services/compression.service.ts, src/cli/services/index.ts, src/cli/tools/dart/index.ts, src/cli/tools/docker/index.ts
=> feat(cli): extract compression service

package.json, src/cli/main.ts, src/cli/proxy.spec.ts, src/cli/proxy.ts, vite.config.ts, yarn.lock
=> feat: support http proxy

src/cli/tools/node/npm.ts, src/cli/tools/node/utils.ts, test/node/Dockerfile
=> feat(node): simplify shell wrapper creation

src/cli/command/index.ts, src/cli/command/install-npm.ts, src/cli/command/utils.ts, src/cli/install-tool/index.ts, src/cli/utils/index.spec.ts, src/cli/utils/index.ts, src/cli/utils/types.ts, src/usr/local/bin/install-containerbase, test/node/Dockerfile
=> feat(cli): add `install-npm` tool

README.md, docs/custom-registries.md
Added docs for custom registries.
More tools to follow.
=> docs: add custom registries

src/cli/tools/ruby/gem.ts, src/cli/tools/ruby/utils.ts, test/ruby/Dockerfile, test/ruby/test/b/Project/Podfile
=> fix(cocoapods): add `activesupport` workaround

src/cli/tools/node/index.ts
new node versions are now without distro, because they are not distro specific
- https://github.com/containerbase/node-prebuild/commit/e42396e7f29814b95f1627a9146565fc94885666
=> feat(node): support distroless prebuilds

src/cli/tools/node/index.ts
- fixes https://github.com/renovatebot/renovate/discussions/25401
=> fix(node): wrong download url for amd64

src/usr/local/containerbase/util.sh, test/bash/util.bats, test/java/Dockerfile
=> fix(java): relax semver validation

test/global-setup.ts
=> test: fix mocking

docs/custom-registries.md
=> docs: document download urls

package.json, patches/@yao-pkg__pkg@5.11.1.patch, pnpm-lock.yaml, src/cli/tools/node/index.ts, src/usr/local/containerbase/util.sh
- https://github.com/yao-pkg/pkg/discussions/25
=> fix: patch `@yao-pkg/pkg` to not change `child_process`

docker-bake.hcl
hopefully fixes arm64 layer cacheing
=> build: optimize docker caching

src/usr/local/containerbase/utils/python.sh
- https://github.com/renovatebot/renovate/discussions/27141#discussioncomment-8441252
=> fix(python): use full python version for install path

src/cli/install-tool/index.ts, src/cli/tools/node/index.ts, src/cli/tools/node/npm.ts, src/cli/tools/node/utils.ts, test/node/Dockerfile
- https://github.com/renovatebot/renovate/discussions/27141#discussioncomment-8441252
=> fix(node)!: use full node version for install path

src/usr/local/containerbase/tools/v2/rust.sh
- validate checksum
- prefer xz files (half download size)
- closes #2068
=> feat(rust): validate download checksum and prefer xz compression

test/flutter/test/d/pubspec.yaml
=> test(flutter): widen `test_api`

src/usr/local/containerbase/utils/filesystem.sh, test/bash/filesystem.bats
=> feat: prepare paths

src/cli/services/path.service.spec.ts, src/cli/services/path.service.ts
preparation for https://github.com/containerbase/base/issues/2713
=> feat(cli): add paths helper

src/cli/tools/node/index.ts
=> feat(node)!: redirect corepack home

src/cli/services/path.service.spec.ts, src/cli/services/path.service.ts, src/usr/local/containerbase/utils/environment.sh
=> feat: support non-root only env vars

src/usr/local/containerbase/bin/install-containerbase.sh, test/latest/Dockerfile
=> feat!: set `XDG_<xxxx>_HOME` variables

docs/cdn.md
=> docs: add cdn docs

docs/custom-registries.md, src/cli/install-tool/index.ts, src/cli/tools/java/maven.ts, test/java/Dockerfile
=> feat(java): add maven version resolver

src/cli/services/path.service.ts, src/cli/tools/node/utils.ts, test/node/Dockerfile
- https://github.com/renovatebot/renovate/discussions/30593
=> fix(cli/npm): support tools with slashes

src/cli/tools/index.ts, test/Dockerfile.distro, test/python/Dockerfile, test/python/Dockerfile.arm64
- https://github.com/renovatebot/renovate/issues/27841
- https://github.com/renovatebot/renovate/pull/30756
=> feat(python): support uv

src/cli/services/compression.service.ts, src/cli/tools/dotnet.ts, test/dotnet/Dockerfile
=> fix: set perms for extracted files

docs/custom-registries.md, src/cli/tools/flutter.ts
=> fix(flutter)!: drop install from source method

docs/custom-registries.md, src/usr/local/containerbase/tools/v2/nix.sh
=> feat(nix)!: drop install support from `hydra.nixos.org`

src/usr/local/containerbase/tools/v2/elixir.sh, src/usr/local/containerbase/tools/v2/sbt.sh, src/usr/local/containerbase/tools/v2/swift.sh, test/erlang/Dockerfile, test/swift/Dockerfile
- Closes #2988
---
```
BREAKING CHANGE: `elixir` and `sbt` are now need a prepare step for rootless install.
```
=> feat!: coerce caches

test/java/Dockerfile
=> test(java): drop mavem archive test

src/cli/command/init-tool.ts, src/cli/prepare-tool/index.spec.ts, src/cli/prepare-tool/prepare-tool.service.ts, src/cli/services/path.service.ts, src/usr/local/containerbase/bin/docker-entrypoint.sh, test/node/Dockerfile, test/node/test/a/package.json
=> fix: init prepared tools from entrypoint

src/usr/local/containerbase/tools/v2/rust.sh, test/rust/Dockerfile
- Closes #3752
⚠️ Once installed those are currently not updated. So needs short lived containers or use docker sidecar.
=> feat(rust): support beta and nightly

src/cli/utils/logger.spec.ts, src/cli/utils/logger.ts
Set log format JSON only when: `CONTAINERBASE_LOG_FORMAT` or the falback `LOG_FORMAT` is set to `json` 
Note: case-insensitive
=> feat: add support for json log formats

docs/custom-registries.md, renovate.json, src/cli/install-tool/index.ts, src/cli/tools/index.ts, src/cli/tools/protoc.ts, src/cli/utils/versions.ts, test/Dockerfile.distro, test/latest/Dockerfile, test/latest/Dockerfile.arm64
fixes https://github.com/renovatebot/renovate/discussions/33694
=> feat(tool): add protoc

.github/workflows/build.yml, docker-bake.hcl
- closes #2084
- successor of #2085
=> ci: run arm64 tests on ubuntu arm runner

src/cli/tools/python/utils.ts
Use pep440 instead of semver, so we can use pep440 ranges in future.
=> fix(python): use pep440 versioning

src/usr/local/containerbase/tools/git.sh
fixes flutter install issues
https://github.com/containerbase/base/actions/runs/13543980224/job/37851208325?pr=4179#step:7:102
=> fix(flutter): set git safe directory

src/cli/install-tool/install-tool.service.ts, test/flux/Dockerfile, test/java/Dockerfile
- closes #4865
Update latest linked version even if install was skipped
=> fix(cli): update latest installed version if already installed

src/cli/command/cleanup-path.spec.ts, src/cli/command/cleanup-path.ts, src/cli/command/file-download.spec.ts, src/cli/command/file-download.ts, src/cli/command/file-exists.spec.ts, src/cli/command/file-exists.ts, src/cli/command/index.spec.ts, src/cli/command/index.ts, src/cli/command/init-tool.spec.ts, src/cli/command/init-tool.ts, src/cli/command/install-gem.spec.ts, src/cli/command/install-gem.ts, src/cli/command/install-npm.spec.ts, src/cli/command/install-npm.ts, src/cli/command/install-pip.spec.ts, src/cli/command/install-pip.ts, src/cli/command/install-tool.spec.ts, src/cli/command/install-tool.ts, src/cli/command/link-tool.spec.ts, src/cli/command/link-tool.ts, src/cli/command/prepare-tool.spec.ts, src/cli/command/prepare-tool.ts, src/cli/command/utils.ts, src/cli/main.ts, src/cli/utils/codes.ts, src/cli/utils/common.spec.ts, src/cli/utils/common.ts, src/cli/utils/index.spec.ts, src/cli/utils/index.ts, src/cli/utils/types.ts
makes future command additions much simpler.
- #4907
=> refactor(cli): simplify command registration

docs/custom-registries.md, src/cli/install-tool/index.ts, src/cli/tools/apko.ts, src/cli/tools/index.ts, test/latest/Dockerfile, test/latest/Dockerfile.arm64
Adds the [`apko`](https://github.com/chainguard-dev/apko) tool
Required for https://github.com/renovatebot/renovate/pull/38142
=> feat: add apko tool

src/usr/local/containerbase/tools/v2/elixir.sh, src/usr/local/containerbase/tools/v2/erlang.sh, src/usr/local/containerbase/tools/v2/git-lfs.sh
=> feat: move v2 tool tests to new test function

src/cli/command/index.ts, src/cli/command/uninstall-gem.spec.ts, src/cli/command/uninstall-gem.ts, src/cli/command/uninstall-npm.spec.ts, src/cli/command/uninstall-npm.ts, src/cli/command/uninstall-pip.spec.ts, src/cli/command/uninstall-pip.ts, src/cli/command/uninstall-tool.spec.ts, src/cli/command/uninstall-tool.ts, src/cli/install-tool/base-install.service.ts, src/cli/install-tool/index.spec.ts, src/cli/install-tool/index.ts, src/cli/install-tool/install-legacy-tool.service.ts, src/cli/install-tool/install-tool.service.ts, src/cli/services/v2-tool.service.ts, src/cli/tools/__mocks__/bun.ts, src/cli/tools/php/__mocks__/composer.ts, src/cli/utils/codes.ts, src/cli/utils/types.ts, src/usr/local/containerbase/bin/install-containerbase.sh, src/usr/local/containerbase/bin/v2-install-tool.sh, src/usr/local/containerbase/utils/v2/defaults.sh, test/di.ts, test/latest/Dockerfile
Add uninstall commands.
- #4907 
---
**TODO**:
=> feat(cli): add `uninstall-tool` command
