containerbase/base

- .github/workflows/build.yaml
- Dockerfile.bionic
- src/usr/local/buildpack/tools/nix.sh
- test/nix/Dockerfile
This was missing from migration 😕
> feat: add nix

- .github/workflows/build.yaml
- Dockerfile
- Dockerfile.apt-cacher
- Dockerfile.bionic
- README.md
- docker-bake.hcl
- src/usr/local/buildpack/util.sh
- test/dotnet/Dockerfile
- test/erlang/Dockerfile
- test/golang/Dockerfile
- test/helm/Dockerfile
- test/java/Dockerfile
- test/latest/Dockerfile
- test/nix/Dockerfile
- test/node/Dockerfile
- test/php/Dockerfile
- test/powershell/Dockerfile
- test/python/Dockerfile
- test/ruby/Dockerfile
- test/rust/Dockerfile
- test/swift/Dockerfile
Allow passing `APT_HTTP_PROXY` to configure a temporary apt proxy while building buildpack based images.
CI is using a local proxy to speedup parallel and multiple downloads.
Maybe we can use github cache to speedup more in a later pr.
> feat: support apt proxy

- .github/workflows/build.yaml
- docker-bake.hcl
- package.json
- tools/buildpack.acl
- tools/prepare-proxy.js
- use squid-deb-proxy instead of apt-cacher-ng
- do not export distro image to docker, saves ~1m (~10%) build time
> ci: switch apt proxy

- src/usr/local/buildpack/util.sh
`squid-deb-proxy` also supports proxying https apt sources, so no need for direct connection.
This works fine on my local ubuntu machines
> fix: use apt proxy for https

- README.md
- src/usr/local/bin/install-tool
- src/usr/local/buildpack/util.sh
- test/latest/Dockerfile
Allows to disable tool installation via build arg: `ARG IGNORED_TOOLS=powershell,node`.
closes #54
> feat: support ignore tools by arg

- Dockerfile.bionic
- src/usr/local/buildpack/tools/gradle.sh
- test/java/Dockerfile
Needed for renovate to install gradle as fallback if no wrapper is found
> feat(java): support `latest` gradle install

- src/usr/local/buildpack/tools/java-jre.sh
- test/java/Dockerfile
You can now install only the JRE part (only java 8 and java 11, SO LTS only)
* v8  JRE is ~40MB where the JDK is ~80MB
* v11 JRE is ~40MB where the JDK is ~180MB
> feat(java): add jre variant installer

- src/usr/local/buildpack/tools/npm.sh
Before:
```
ubuntu@ab818ffd2bfa:/$ install-tool npm 6.14.3
Installing tool npm v6.14.3
added 1 package, and audited 436 packages in 7s
1 package is looking for funding
run `npm fund` for details
22 vulnerabilities (1 low, 15 moderate, 6 high)
To address issues that do not require attention, run:
npm audit fix
To address all issues (including breaking changes), run:
npm audit fix --force
Run `npm audit` for details.
npm notice
npm notice New patch version of npm available! 8.1.0 -> 8.1.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.3
npm notice Run npm install -g npm@8.1.3 to update!
npm notice
8.1.0
npm WARN using --force Recommended protections disabled.
rm: cannot remove '/root/.cache': Permission denied
ubuntu@ab818ffd2bfa:/$ npm --version
6.14.3 …
```
> fix: npm non-root install

- Dockerfile
- docs/custom-base-image.md
- src/usr/local/bin/docker-entrypoint.sh
- src/usr/local/bin/install-buildpack
- src/usr/local/buildpack/util.sh
- test/Dockerfile.bionic
- test/latest/Dockerfile
* Instead of relying on `BASH_ENV` we now use the known `ENV_FILE=/usr/local/etc/env` path
* Add `/home/<user>/bin` to default path
* Add `ENV=/usr/local/etc/env` for interactive dash shell (default /bin/sh`)
> feat: update env handling

- src/usr/local/buildpack/tools/lerna.sh
- src/usr/local/buildpack/tools/pnpm.sh
- src/usr/local/buildpack/tools/yarn.sh
- test/node/Dockerfile
Use versioned tool folders for `yarn` , `pnpm` and `lerna`. They support npm ranges.
> feat(node): use versioned folders

- src/usr/local/bin/install-npm
- src/usr/local/buildpack/tools/lerna.sh
- src/usr/local/buildpack/tools/node.sh
- src/usr/local/buildpack/tools/npm.sh
- src/usr/local/buildpack/tools/pnpm.sh
- src/usr/local/buildpack/tools/yarn.sh
- src/usr/local/buildpack/util.sh
- test/node/Dockerfile
- test/node/test/a/package.json
- ref #213 
`PATH` search order:
- `/home/<user>/.npm-global/bin` (user `npm install -g`)
- `/home/<user>/bin` (user install)
- `/usr/local/bin` (root install)
global prefix is now `/usr/local`, so `install-npm npm` overwrites `/usr/local/bin`
> feat(node): use symlinks for tools

- docker-bake.hcl
- src/usr/local/buildpack/tools/node.sh
- src/usr/local/buildpack/util.sh
- test/node/Dockerfile
> feat(node): allow runtime install

- src/usr/local/buildpack/tools/git-lfs.sh
- test/Dockerfile.bionic
The test before claimed that `git-lfs` is already installed, even if it was not.
> fix: properly test for installed git-lfs

- .husky/pre-commit
@viceice Please review.
I took some lines from the Renovate `pre-commit` hook: https://github.com/renovatebot/renovate/blob/main/.husky/pre-commit
`#!/bin/bash` was needed for the array of files.
> feat: add shellcheck pre-commit command

- .husky/pre-commit
Small fix for the pre-commit hook to use the correct syntax for passing an array to shellcheck
> chore: fix preCommit script for shellcheck

- src/usr/local/bin/install-tool
- src/usr/local/buildpack/utils/defaults.sh
This adds the new tools contract only.
When a tool is located in `/usr/local/buildpack/tools/v2/<TOOL>.sh` then it is considered a new tool (in terms of contract) and will be installed with the methods defined in the `defaults.sh`.
When the tool is available in the old and new path, then the new path is preferred.
> feat: add new tool contract

- src/usr/local/buildpack/utils/linking.sh
@viceice This somehow got introduced while I did the utils splitting or during our shellcheck changes.
This should fix the linking against `/bin/<tool>`
> fix: use valid path for linking

- src/usr/local/bin/install-buildpack
- src/usr/local/buildpack/util.sh
- src/usr/local/buildpack/utils/environment.sh
Moves the setup for the env file into the `environment.sh` helper file.
This is needed to setup proper testing with bats
> refactor: move setup for env files to helper file

- src/usr/local/bin/install-tool
This fixes a problem when v2 tools are used at this stage.
We should source the v2 tool file instead of the old one.
Additionally we will always link the tool, regardless if it already linked or not until we have proper versioning.
> fix: use correct v2 tool file during install

- src/usr/local/buildpack/util.sh
- src/usr/local/buildpack/utils/environment.sh
- src/usr/local/buildpack/utils/version.sh
- test/bash/version.bats
This adds support to set versions for the tools and to query them
This is useful to detect if we need to link the tools again and can possibly help with further Renovate use cases.
> refactor: add version helper with tests

- src/usr/local/buildpack/utils/cache.sh
- test/bash/cache.bats
When we call `cleanup_cache` it should silently return instead of abort.
> fix: do not abort if cache var is empty

- src/usr/local/buildpack/tools/erlang.sh
- test/Dockerfile.bionic
- test/erlang/Dockerfile
> feat: new erlang install method

- src/usr/local/bin/install-buildpack
- src/usr/local/buildpack/utils/constants.sh
- src/usr/local/buildpack/utils/filesystem.sh
- test/bash/cache.bats
- test/bash/environment.bats
- test/bash/filesystem.bats
- test/bash/linking.bats
- test/bash/util.bats
- test/bash/v2/filesystem.bats
- test/bash/version.bats
- test/latest/Dockerfile
Changes the bin path from `/opt/buildpack/bin` to `/usr/local/bin` as discussed in #300
> fix: use /usr/local/bin as bin path

- test/bash/tools/helm.bats
Makes the helm bats tests versioned by Renovate
Closes #326
> chore: enable Renovate on helm bats files

- src/usr/local/buildpack/tools/poetry.sh
Moves the install url to the new location promoted by the poetry team.
Closes #339
> fix: use new poetry install url

- src/usr/local/buildpack/utils/linking.sh
- test/bash/linking.bats
* Sets the correct path for shell wrappers
* Adds test for the shell wrapper
* sets the permissions to `775` for the shell wrappers
Closes #338
> fix: shell wrapper has 775 permissions for overwrites

- src/usr/local/bin/install-npm
- src/usr/local/buildpack/tools/lerna.sh
- src/usr/local/buildpack/tools/node.sh
- src/usr/local/buildpack/tools/npm.sh
- src/usr/local/buildpack/tools/pnpm.sh
- src/usr/local/buildpack/tools/yarn-slim.sh
- src/usr/local/buildpack/tools/yarn.sh
- src/usr/local/buildpack/utils/node.sh
- test/node/Dockerfile
preparation for 
- #346
- #338
bats tests can be added later after migration to v2 scripts
> feat(node): refactor prefix handling

- src/usr/local/buildpack/tools/v2/erlang.sh
- src/usr/local/buildpack/utils/environment.sh
Reads the environment for v1 and v2 tools as well as the user directory
Priority list from least to most priority:
* `/usr/local/env.d/`
* `/opt/buildpack/env.d/`
* `${USER_HOME}/env.d/`
Closes #377
> fix: read v1 and v2 environment variables

- test/bash/cache.sh
- test/bash/tools/flux.bats
- test/bash/tools/helm.bats
Example usage for local testing:
```bash
export TEST_CACHE_DIR=/tmp/renovate/bats
yarn bats
```
Reduces the bats testing from 16 to 6 seconds when the cache if filled.
> chore: allow bats tests to use a global cache dir

- src/usr/local/buildpack/tools/v2/erlang.sh
- src/usr/local/buildpack/utils/v2/overrides.sh
- test/erlang/Dockerfile
- readd support for erlang v22
- skip system deps, they aren't required
> fix(erlang): support v22 and skip non-required system deps

- src/usr/local/buildpack/tools/v2/python.sh
- test/python/Dockerfile
- test/python/test/h-pipenv/Pipfile
- test/python/test/h-pipenv/Pipfile.lock
move `PYTHONHOME` to shell wrapper.
- fixes #461
> fix(python): refactor env handling

- src/usr/local/buildpack/tools/v2/python.sh
- src/usr/local/buildpack/utils/install.sh
- test/python/Dockerfile
While installing an already present version of python with `install-tool`, the linking process fails (if it is called, i.e. if there is a mismatch between the current version and the one to be installed) because the `MAJOR` and `MINOR` env variables are not set and the constructed path is invalid:
```bash
function link_tool () {
...
python_shell_wrapper "${TOOL_NAME}${MAJOR}" "${versioned_tool_path}"
python_shell_wrapper "${TOOL_NAME}${MAJOR}.${MINOR}" "${versioned_tool_path}"
```
These variables are set by the `check_semver` function, that is called by the `check_tool_requirements` in the `install_v2_tool` (`src/usr/local/buildpack/utils/install.sh`), but that invocation is skipped when the tool is already present and only requires linking.
This change adds a suitable test and the …
> fix: allow linking an already installed version

- package.json
- src/usr/local/buildpack/utils/cache.sh
- src/usr/local/buildpack/utils/java.sh
- test/bash/cache.bats
- test/bash/java.bats
- test/java/Dockerfile
fix modern java version handling[^1]
* `18.0.2+101` => `18.0.2.1+1`
[^1]: https://github.com/adoptium/api.adoptium.net/issues/492
> fix(java): handle modern versions

- src/usr/local/bin/docker-entrypoint.sh
- src/usr/local/bin/install-buildpack
- src/usr/local/buildpack/tools/v2/python.sh
- src/usr/local/buildpack/util.sh
- src/usr/local/buildpack/utils/environment.sh
- src/usr/local/buildpack/utils/linking.sh
- src/usr/local/buildpack/utils/ruby.sh
- test/ruby/Dockerfile
- use new env  `CONTAINERBASE_ENV` to detect if we've loaded our env file
- export `CONTAINERBASE=1` additionally to `BUILDPACK=1` for external tool usage (like renovate)
- ruby and python are now used default shell wrapper
> feat: simplify env and shell handling

- .github/workflows/build.yml
- src/usr/local/bin/install-pip
- src/usr/local/buildpack/tools/v2/hashin.sh
- src/usr/local/buildpack/tools/v2/pip-tools.sh
- src/usr/local/buildpack/tools/v2/pipenv.sh
- src/usr/local/buildpack/tools/v2/python.sh
- src/usr/local/buildpack/utils/python.sh
- test/python/Dockerfile
> feat(python): simlify install and add hashin, pip-tools, pipenv

- src/usr/local/buildpack/utils/prepare.sh
If a tool is skipped via `IGNORED_TOOLS` and we run `install-tool all` the whole process exit's early instead of preparing other tools.
> fix(prepare-tool): don't break early when skip tool

- src/usr/local/buildpack/tools/v2/swift.sh
- test/Dockerfile.arm64
> feat(swift): support arm64

- src/usr/local/buildpack/tools/v2/flutter.sh
- src/usr/local/buildpack/tools/v2/swift.sh
- test/Dockerfile.arm64
- test/Dockerfile.jammy
- test/flutter/Dockerfile
> feat(flutter): support arm64

- docker-bake.hcl
- tools/prepare-release.js
- tools/publish-release.js
- closes #700
- closes #711
BREAKING CHANGE: `containerbase/buildpack` is no longer published
> feat!: publish multiarch image

- src/usr/local/buildpack/tools/v2/erlang.sh
we now create checksum files for our prebuild binaries
> feat(erlang): validate checksum

- src/usr/local/buildpack/tools/v2/python.sh
- test/python/Dockerfile
Older python (like 3.6.15) comes with an older `pip`, so the `--use-pep517` flag isn't supported.
We now use `PIP_USE_PEP517=true` env to force the flag, which is ignored by older `pip`.
> fix(python): support older pip versions for pep517

- src/usr/local/buildpack/tools/v2/maven.sh
older versions are removed from `downloads.apache.org`
> fix(maven): use `archive.apache.org` for downloads

- src/usr/local/buildpack/tools/v2/pdm.sh
- test/Dockerfile.jammy
- test/python/Dockerfile
- Adds PDM for usage by the new PEP621 manager
- replaces h3py with h5py for tests as the former is no longer available
> feat(tools): add PDM to tools

- README.md
- src/cli/services/env.service.ts
- src/cli/services/http.service.spec.ts
- src/cli/services/http.service.ts
- test/latest/Dockerfile
- #1067
this PR adds support for url replace for docker tool
> feat: support url replace via env

- package.json
- src/cli/services/http.service.spec.ts
- src/cli/services/http.service.ts
- src/cli/utils/hash.spec.ts
- src/cli/utils/hash.ts
- test/path.ts
- yarn.lock
> fix(http): compute checksum after download

- .devcontainer/devcontainer.json
The following changes have been made: 
- Use of properties `settings` and `extensions` at the top level has been deprecated and moved under [customizations](https://containers.dev/supporting).
- `terminal.integrated.shell.linux` has been deprecated in favor of `terminal.integrated.defaultProfile.linux`.
> chore: refactor devcontainer to remove warnings

- src/usr/local/containerbase/utils/cache.sh
only output download logs from containerbase tool on error
> fix: buffer download logs

- docs/custom-root-ca.md
- src/usr/local/containerbase/tools/v2/node.sh
- test/latest/Dockerfile
- test/latest/src/etc/nginx/sites-enabled/default
- tools/esbuild.js
Using `NODE_EXTRA_CA_CERTS` is no longer required.
Using `NODE_OPTIONS=--use-openssl-ca` is known to be broken on Node `>=18.0.0 <18.5.0`[^1]
[^1]: https://nodejs.org/en/blog/vulnerability/july-2022-security-releases#openssl---aes-ocb-fails-to-encrypt-some-bytes-mediumcve-2022-2097
> feat(node): enable use-openssl-ca

- src/cli/command/index.ts
- src/cli/command/install-gem.spec.ts
- src/cli/command/install-gem.ts
- src/cli/install-tool/index.ts
- src/cli/install-tool/install-tool-base.service.ts
- src/cli/tools/index.ts
- src/cli/tools/ruby/gem.ts
- src/cli/tools/ruby/utils.ts
- src/cli/utils/common.spec.ts
- src/cli/utils/index.spec.ts
- src/cli/utils/index.ts
- src/cli/utils/types.ts
- src/usr/local/bin/install-containerbase
- src/usr/local/containerbase/tools/v2/bundler.sh
- src/usr/local/containerbase/tools/v2/cocoapods.sh
- test/ruby/Dockerfile
> feat(ruby): convert gem tools and add install-gem command

- src/usr/local/containerbase/tools/v2/python.sh
- test/python/test/h-pipenv/Pipfile
- test/python/test/h-pipenv/Pipfile.lock
- Fixes #98
- Closes#594
I have created a new this one because #594 is inactive.
This will install the dependency libraries for mysqlclient and psycopg2 in the image.
> feat(python): Add libmysqlclient-dev libpq-dev for Python

- src/cli/prepare-tool/prepare-tool-base.service.ts
- src/cli/tools/dart/index.ts
- src/cli/tools/docker/index.ts
- src/cli/tools/dotnet/index.ts
- src/cli/tools/flutter.ts
> refactor: move constructor injections

- src/cli/tools/node/index.ts
- src/cli/tools/node/npm.ts
- src/cli/tools/node/utils.ts
- https://github.com/renovatebot/renovate/releases/tag/37.234.0
- re2 now has official linux arm64 support
> feat(node): drop renovate re2 mirror on newer versions

- .github/workflows/build.yml
The matrix tests are very flaky sometimes, so don't cancel other's for faster retries
> ci: don't fail fast

- src/usr/local/containerbase/tools/v2/golang.sh
- remove `GOSUMDB=off` and `CGO_ENABLED=0`
- set `GOPATH=/opt/containerbase/home/go`
- closes #2662
- closes #2663
- #2713
> feat(golang)!: change paths

- src/cli/tools/ruby/utils.ts
`RUBYGEMS_HOST` is only used for gem push, so we need to use cli args 😕
> fix(ruby): correctly pass source url to gem command

- src/cli/install-tool/install-legacy-tool.service.ts
- src/cli/services/env.service.spec.ts
- src/cli/services/env.service.ts
- src/cli/tools/node/utils.ts
- src/cli/tools/ruby/utils.ts
This allows to enable the cdn for those managers selectively.
- #972
> feat(cdn): add config for `gem`, `npm` and `pip`

- src/usr/local/containerbase/tools/v2/elixir.sh
Elixir v1.17.0 just released. The install script is failing because the OTP version if/else block isn't up-to-date.
Renovate is effectively broken for Elixir right now: https://github.com/sheerlox/elixir_renovate_demo/pull/6
Renovate log from the PR above (Mend Renovate job id `7e88e954-625d-4a07-804b-45eefc1a151c`):
```
[17:27:45.046] INFO (193): Installing tool elixir@1.17.0...
installing v2 tool elixir v1.17.0
Download failed: https://github.com/elixir-lang/elixir/releases/download/v1.17.0/elixir-otp-24.zip
[17:27:45.616] INFO (221): Downloading file ...
url: "https://github.com/elixir-lang/elixir/releases/download/v1.17.0/elixir-otp-24.zip"
output: "/tmp/renovate/cache/containerbase/f7649696d9e36012fd17fe14a3344673897f8c089328bc8a15abaf579e0f5ab1/elixir-otp-24.zip"
[17:27:45.764] …
```
> fix: add support for Elixir v1.17.0

- docs/custom-registries.md
- src/usr/local/containerbase/tools/v2/golang.sh
- Use github prebuild go (only repacked for containerbase)
- Add checksum validation
- closes #2062
> feat(golang): use prebuild go and validate checksums

- docs/custom-registries.md
- src/usr/local/containerbase/tools/v2/nix.sh
Renovate currently fails to download Nix because the URL for the latest version has been updated.
```
WARN: Error updating flake.lock (branch="renovate/lock-file-maintenance")
{
"err": {
"cmd": "/bin/sh -c install-tool nix 2.24.1",
"stderr": "",
"stdout": "installing v2 tool nix v2.24\n[12:53:34.669] INFO (53): Installing tool nix@2.24.1...\nDownload failed: https://hydra.nixos.org/job/nix/maintenance-2.24/buildStatic.x86_64-linux/latest/download-by-type/file/binary-dist\nDownload failed, retrying\nDownload failed: https://hydra.nixos.org/job/nix/maintenance-2.24/buildStatic.x86_64-linux/latest/download-by-type/file/binary-dist\nDownload failed, retrying\nDownload failed: https://hydra.nixos.org/job/nix/maintenance-2.24/buildStatic.x86_64-linux/latest/download-by-type/file/binary-dist\nDow …
```
> fix(nix): update path to hydra build for 2.24 and newer

- docs/custom-registries.md
- src/usr/local/containerbase/tools/v2/nix.sh
> feat(nix): use our own prebuilds

- src/usr/local/containerbase/tools/git.sh
New additional signing key since 2024-04
https://launchpad.net/~git-core/+archive/ubuntu/ppa?field.series_filter=focal
> fix(git): use modern apt config

- docs/custom-registries.md
- src/cli/tools/php/composer.ts
> fix(php)!: drop `getcomposer.org` download support

- docs/custom-base-image.md
- src/cli/services/env.service.spec.ts
- src/cli/services/env.service.ts
- src/usr/local/containerbase/bin/install-containerbase.sh
- test/bash/filesystem.bats
- test/bash/util.sh
- test/bash/v2/filesystem.bats
- test/dart/Dockerfile
- test/dotnet/Dockerfile
- test/erlang/Dockerfile
- test/flutter/Dockerfile
- test/flux/Dockerfile
- test/golang/Dockerfile
- test/helm/Dockerfile
- test/java/Dockerfile
- test/jb/Dockerfile
- test/latest/Dockerfile
- test/nix/Dockerfile
- test/node/Dockerfile
- test/php/Dockerfile
- test/powershell/Dockerfile
- test/python/Dockerfile
- test/ruby/Dockerfile
- test/rust/Dockerfile
- test/swift/Dockerfile
- closes #3277
---
```
BREAKING CHANGE: the default user id is now `12021`.
```
> feat!: switch default userid to `12021`

- src/cli/tools/java/index.ts
- test/java/Dockerfile
- tools/test.js
It previously always tried to write the gradle env because it checked the wrong file existance
> fix(java): wrong gradle init

- docs/custom-registries.md
- src/cli/tools/dotnet.ts
- test/dotnet/Dockerfile
This is probably a breaking change for url replacement users. 🤷‍♂️ 
- Closes #3866
> fix(dotnet): use new cdn url

- src/cli/tools/node/index.ts
- src/cli/tools/node/utils.ts
Pass  `--use-openssl-ca` via `NODE_OPTIONS`, which can be overridden from outer env.
I'm not sure, but `NODE_OPTIONS` can maybe no longer set via renovate options. 🤔 
- closes #4033
> fix(node): use `NODE_OPTIONS` for `--use-openssl-ca`

- src/cli/install-tool/index.ts
- src/cli/tools/python/pip.ts
- src/cli/tools/python/poetry.ts
- src/cli/tools/python/schema.ts
Fixes recent ci errors, because `poetry-plugin-pypi-mirror` isn't compatibe with `poetry>=2.1.0`.
next step is to respect the python dependency.
> fix(poetry): check plugins when resolving poetry version

- src/cli/tools/python/utils.ts
update workaround because of upstream fix
- #4470
- https://github.com/pypa/virtualenv/releases/tag/20.31.2
> fix(python/poetry): update virtualenv version range

- package.json
- patches/@semantic-release__github.patch
- pnpm-lock.yaml
Workaround for
- https://github.com/semantic-release/github/issues/817
> build: add workaround for latest github release from maintenance branch
